[build]
publish = "dist"
command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure image paths work correctly
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
